### ISSUE TITLE
Full Article

### ISSUE THREAD

**Issue by ghost** [BaunCMS/Baun-Blog-Rss#2]
Is there a way to get the full article in the feed?

**Comment by marksouthard** [comment]
You could edit the plugin so that this line is updated to use the content and not the description:

https://github.com/BaunCMS/Baun-Blog-Rss/blob/master/src/templates/feed.html#L14

**Comment by ghost** [comment]
OK but what variable must i use for it

Am 24. Juli 2017 16:45:45 MESZ schrieb Mark Southard <notifications@github.com>:
>You could edit the plugin so that this line is updated to use the
>content and not the description:
>
>https://github.com/BaunCMS/Baun-Blog-Rss/blob/master/src/templates/feed.html#L14
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BaunCMS/Baun-Blog-Rss/issues/2#issuecomment-317445971

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marksouthard** [comment]
```{{ post.content }}```

**Comment by ghost** [comment]
I tried this but no output.

Am 24. Juli 2017 17:00:26 MESZ schrieb Mark Southard <notifications@github.com>:
>```{{ post.content }}}```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BaunCMS/Baun-Blog-Rss/issues/2#issuecomment-317450878

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by marksouthard** [comment]
Any chance you could dump out the `post` var; the best I can remember it should be content. I'm sorry, but I've not been into this project much recently.

**Comment by ghost** [comment]
I will try soon
Then I am coming back

Am 24. Juli 2017 17:09:24 MESZ schrieb Mark Southard <notifications@github.com>:
>Any chance you could dump out the `post` var; the best I can remember
>it should be content. I'm sorry, but I've not been into this project
>much recently.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/BaunCMS/Baun-Blog-Rss/issues/2#issuecomment-317454040

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by ghost** [comment]
it looks like there is no way:

```
  [0]=>
  array(6) {
    ["route"]=>
    string(19) "blog/neues-cms-blog"
    ["path"]=>
    string(31) "blog/20170724-neues-cms-blog.md"
    ["title"]=>
    string(16) "Neues CMS & Blog"
    ["info"]=>
    array(2) {
      ["title"]=>
      string(16) "Neues CMS & Blog"
      ["description"]=>
      string(40) "Ich nutze ein neues CMS & ein neuen Blog"
    }
    ["excerpt"]=>
    string(174) "Eigentlich war ich ja ganz zufrieden mit Hugo, doch war es mir immer noch zu gewaltig.
Zusätzlich brauchte ich immer den Zugang zu meinem Server via SSH oder FTP um einen..."
    ["published"]=>
    string(14) "24th July 2017"
  }
```

**Comment by ghost** [comment]
Ok, I fixed it I will make a Pull Request to the Framework.

**Comment by marksouthard** [comment]
Awesome! Thanks.
